### ISSUE TITLE
[public OHDSI QueryLibrary] Queries don't render when selecting them.

### ISSUE THREAD

**Issue by w0ut0** [OHDSI/QueryLibrary#18]
The [public OHDSI QueryLibrary](https://data.ohdsi.org/QueryLibrary/) seems down. When clicking on a query, we get the error message `ERROR: An error has occurred. Check your logs or contact the app author for clarification.`

I can replicate this issue on Chrome, Edge Chromium and Firefox. There are no additional messages in the console.

**Comment by leeevans** [comment]
Below are the OHDSI shiny log error messages to help with troubleshooting.

The main error appears to be:

```
File www/rendered.css not found in resource path
Warning: Error in : pandoc document conversion failed with error 99
```

Note. The OHDSI shiny server was recently updated to use "rocker/shiny:4.1.0" in order to accomodate cohortdiagnostics package dependency R (>= 4.0.0).

```
Warning: 'renderSql' is deprecated.
Use 'render' instead.
See help("Deprecated")
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'querylibrary-rendered.knit' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
File www/rendered.css not found in resource path
Warning: Error in : pandoc document conversion failed with error 99
  119: stop
  118: stop2
  117: pandoc_convert
  116: convert
  115: rmarkdown::render
  114: createRenderedHtml
  113: <reactive> [/srv/shiny-server/QueryLibrary/server.R#56]
   97: renderedFilename
   96: renderText [/srv/shiny-server/QueryLibrary/server.R#64]
   95: func
   82: renderFunc
   81: output$html
    1: runApp
```

**Comment by leeevans** [comment]
Also tagging @bmosseveld who was the last committer on the QueryLibrary shiny app in the ShinyDeploy github repo:
https://github.com/OHDSI/ShinyDeploy/commits?author=bmosseveld

**Comment by bmosseveld** [comment]
I solved this issue in the EHDEN github repository. @schuemie I don't know how to synchronize it with the OHDSI repository and if there have been any changes in the OHDSI repository.

**Comment by schuemie** [comment]
@bmosseveld : you should be able to create a pull request (In the EHDEN/QueryLibrary, click 'Pull Requests' and then 'New pull request') that target's the OHDSI repo. This should also tell you if there are conflicts (which I don't think there are).

**Comment by Tofunmi19** [comment]
Hi, I am still having issues accessing this [https://data.ohdsi.org/QueryLibrary/](url)
I get the error: `An error has occurred. Check your logs or contact the app author for clarification.`
Any ideas on how to fix this?
Thanks.

**Comment by bmosseveld** [comment]
@schuemie ; Hi Martijn,
When I do new pull request I get:

base repository: OHDSI/QueryLibrary base: master  <- head repository EHDEN/QueryLibrary compare: master
Able to merge. These branches can be automatically merged.

Below that I see an older pull request (probably done by Peter Rijnbeek) and a list of older commits but I don't see a button or link to actually do the pull request.
![Pull Request](https://user-images.githubusercontent.com/7286241/129530202-02fb2193-cb08-4da3-b964-68335bb6cca3.jpg)

**Comment by Urban90** [comment]
Hi, me too, I am still having issues accessing this https://data.ohdsi.org/QueryLibrary/
I also get the error: An error has occurred. Check your logs or contact the app author for clarification.
Can you please help me in fixing this?
Thanks you.

**Comment by bmosseveld** [comment]
It should be working now.

**Comment by yampeku** [comment]
At 20211109 I'm still seeing the same error message reported by @Urban90

**Comment by bmosseveld** [comment]
Should now be solved.

**Comment by yampeku** [comment]
I think error is still present in the deployed version at https://data.ohdsi.org/QueryLibrary/

**Comment by bmosseveld** [comment]
Yes I see but I cannot replace the deployed version at data.ohdsi.org.

**Comment by leeevans** [comment]
Hi @bmosseveld - the deployed version at data.ohdsi.org is in the below github directory:
https://github.com/OHDSI/ShinyDeploy/tree/master/QueryLibrary
If you can create a Pull Request and apply the same fix there, it will auto-deploy when the PR is merged and solve the problem.

**Comment by bmosseveld** [comment]
Hi @leeevans - What should then be the reference for deploy repository? I tried OHDSI/ShinyDeploy/tree/master/QueryLibrary an OHDSI/ShinyDeploy/QueryLibrary but they both didn't work.

**Comment by leeevans** [comment]
@bmosseveld if you are trying to create a pull request directly from this repo to the OHDSI/ShinyDeploy repo, I don't think that will work - unless someone with more advanced GitHub knowledge knows a way (@schuemie ?)

The issue is that the QueryLibrary shiny app is deployed in a sub-directory in the OHDSI/ShinyDeploy repo.

The following approach should work:
 
- fork the OHDSI/ShinyDeploy repo in GitHub
- git clone the OHDSI/ShinyDeploy fork repo master branch to local pc
- copy over the changed file(s) from OHDSI/QueryLibrary GitHub repo relevant commit to the OHDSI/ShinyDeploy fork clone QueryLibrary sub-directory on local pc
- commit and push the updated local OHDSI/ShinyDeploy clone changes back to the GitHub fork
- create a pull request from the updated OHDSI/ShinyDeploy gitHub fork to the original GitHub OHDSI/ShinyDeploy master branch

**Comment by bmosseveld** [comment]
The pull request is made.

**Comment by leeevans** [comment]
@bmosseveld and @PRijnbeek  thanks for updating the QueryLibrary code in the OHDSI/ShinyDeploy github.

Unfortunately the shiny application is not working due to the below error. I believe the issue is because the application is trying to write out a file (rendered.Rmd') in the shiny application code sub-directory (/srv/shiny-server/QueryLibrary/www) instead of the shiny server '/tmp' directory which is writable.

The shiny application code directory is read-only as a security policy on the public OHDSI shiny server.

Error Message:

Warning in writeLines(output, con <- file(paste0(getwd(), "/www/rendered.Rmd"))) :
  cannot open file '/srv/shiny-server/QueryLibrary/www/rendered.Rmd': Permission denied
Warning: Error in writeLines: cannot open the connection
  115: writeLines
  114: createRenderedHtml
  113: <reactive> [/srv/shiny-server/QueryLibrary/server.R#56]
   97: renderedFilename
   96: renderText [/srv/shiny-server/QueryLibrary/server.R#64]
   95: func
   82: renderFunc
   81: output$html
    1: runApp
Warning in .getReactiveEnvironment() :
  closing unused connection 3 (/srv/shiny-server/QueryLibrary/www/rendered.Rmd)

**Comment by bmosseveld** [comment]
Thanks Lee!
I already noticed that it didn't work. I will look into that.

**Comment by bmosseveld** [comment]
@leeevans It should now write it's temporary files to /tmp but it still does not work. Can you see what kind of error occurs?

**Comment by leeevans** [comment]
@bmosseveld please see the error message below. 

(Note. The file 'rendered.css ' exists here: "/srv/shiny-server/QueryLibrary/www/rendered.css").

Error message:

File rendered.css not found in resource path
Warning: Error in : pandoc document conversion failed with error 99
  119: stop
  118: stop2
  117: pandoc_convert
  116: convert
  115: rmarkdown::render
  114: createRenderedHtml
  113: <reactive> [/srv/shiny-server/QueryLibrary/server.R#56]
   97: renderedFilename
   96: renderText [/srv/shiny-server/QueryLibrary/server.R#64]
   95: func
   82: renderFunc
   81: output$html
    1: runApp

**Comment by bmosseveld** [comment]
@leeevans  I hope I have solved it now. I made a new pull request. Can you merge it?

**Comment by bmosseveld** [comment]
It works!
Thanks @leeevans !
